language: python

sudo: required
dist: trusty

addons:
  apt:
    packages:
    - unixodbc
    - unixodbc-dev
    - freetds-dev
    - freetds-bin
    - tdsodbc

matrix:
    include:
        - env: ELASTIC2X
          python: "3.5"
          addons:
              apt:
                  sources:
                      - elasticsearch-2.x
                      - mongodb-3.0-precise
                  packages:
                      - elasticsearch
                      - mongodb-org-server

        - env: ELASTIC17
          python: "3.4"
          addons:
              apt:
                  sources:
                      - elasticsearch-1.7
                      - mongodb-3.0-precise
                  packages:
                      - elasticsearch
                      - mongodb-org-server


        - env: ELASTIC17
          python: "3.5"
          addons:
              apt:
                  sources:
                      - elasticsearch-1.7
                      - mongodb-3.0-precise
                  packages:
                      - elasticsearch
                      - mongodb-org-server


services:
    - elasticsearch
    - redis-server

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.npm

before_install:
    - nvm install node
    - nvm use node
    - node --version
    - npm install -g npm@latest
    - npm install -g grunt-cli
    - pip install requests
    - export DISPLAY=:99.0
    - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1920x1080x24
    - ./scripts/get-chrome-url | wget -N --no-verbose -i -
    - unzip chrome-linux.zip
    - export CHROME_BIN=`pwd`/chrome-linux/chrome
    - $CHROME_BIN --version

install:
    - cd server && pip install -r dev-requirements.txt && cd ..
    - cd client && npm install --python=python2.7 && cd ..

before_script: >
    df -h
    && sudo sed -i 's\enabled: true\enabled: false\' /etc/mongod.conf
    && sudo service mongod restart

script:
    - cd client && npm test && cd ..
    - cd server && flake8 && cd ..
    - cd server && time behave ./features/ --format progress2 --logging-level ERROR && cd ..
    - cd server && time nosetests && cd ..
    - cd client && grunt build && cd ..
    - cd server && python manage.py users:create -u test -p test -e test@localhost --admin && cd ..

after_script:
    - rm .npm/*.lock
